name: Deploy Serverless Infra
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      # Déploiement Pulumi (CLI auto-installée par l'action)
      - name: Pulumi Up
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: dev              # sélectionne la stack
          upsert: true                 # la crée si elle n'existe pas
          refresh: true                # équivaut à --refresh
          message: "CI deploy"
          # pose la config (remplace 'pulumi config set aws:region ...')
          config-map: |
            {"aws:region":"${{ env.AWS_REGION }}"}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}